---
- name: Enforce S3 versioning policy on AWS
  hosts: localhost

  tasks:
    - name: List S3 buckets in AWS
      amazon.aws.s3_bucket_info:
      register: S3_List
    
    - debug:
        var: S3_List
    
    - name: Enable versioning on S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ item.name }}"
        versioning: yes
      loop: "{{ S3_List.buckets }}" 
